example/android/app/build.gradle
example/ios/Podfile.lock
example/ios/TreeMultiSelectExample.xcodeproj/project.pbxproj
example/package.json
example/src/App.tsx
example/src/sample/sampleData3.ts
package.json
src/TreeView.tsx
src/components/CheckboxView.tsx
src/components/NodeList.tsx
src/helpers/index.ts
src/helpers/search.helper.ts
src/signals/global.signals.ts
src/types/treeView.types.ts

- Memoized all signal effects
- Added multi-key filtering feature
- Added missing signal cleanup on TreeView cleanup
- Re-enabled checkbox animations as optimizations now support smooth animations

Significant performance optimizations in tree filtering and selection and some more feature

---

.github/workflows/ci.yml

- chore: prevent auto version increment in github actions

chore: prevent auto version increment in github actions

---

.github/workflows/ci.yml

- chore: remove unnecessary package json add in github action

chore: remove unnecessary package json add in github action

---

.github/workflows/ci.yml
package.json

- chore: added npm publish provenance to gh action

chore: added npm publish provenance to gh action

---

.github/workflows/ci.yml

- chore: updated gh actions to ignore peer deps in npm install

chore: updated gh actions to ignore peer deps in npm install

---

.github/workflows/ci.yml

- chore: removed npm install in favor of npm ci in gh action

chore: removed npm install in favor of npm ci in gh action

---

.github/workflows/ci.yml

- chore: added permission to npm publish job

chore: added permission to npm publish job

---

.github/workflows/ci.yml
package.json

- chore: updated gh action to have write permission to contents to allow tag writing

chore: updated gh action to have write permission to contents to allow tag writing

---

.github/workflows/ci.yml
package.json

- chore: updated gh action npm publish steps

chore: updated gh action npm publish steps

---

.github/workflows/ci.yml
package.json

- chore: gh action changelog generate sequence updated

chore: gh action changelog generate sequence updated

---

package-lock.json
package.json
yarn.lock

- chore: added missing semnatic-release module

chore: added missing semnatic-release module

---

.github/workflows/ci.yml
README.md
package.json

- docs: added hyperlink to properties section of readme

docs: added hyperlink to properties section of readme

---

README.md

- docs: updated readme image alignment

docs: updated readme image alignment

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
README.md
example/ios/Podfile.lock
example/yarn.lock
package-lock.json
package.json
release.config.js
yarn.lock

- Updated readme and fixed semantic release config

Updated readme and fixed semantic release config

---

package.json
release.config.js

- fix: workflow action not upgrading package json version

fix: workflow action not upgrading package json version

---

example/yarn.lock
package-lock.json
src/helpers/flattenTree.helper.ts
yarn.lock

- perf: optimized flatten tree helper func

perf: optimized flatten tree helper func

---

CHANGELOG.md
package-lock.json
package.json

* fixed updated data state not reflecting due to issues in deep compare effect ([fb5a745](https://github.com/JairajJangle/react-native-tree-multi-select/commit/fb5a745bf494cd3dec15e68fc05fa1a17034f75d))
* made data prop reactive ([f5f3699](https://github.com/JairajJangle/react-native-tree-multi-select/commit/f5f369996e5c67b32c87caa0edad6131d037f1a9))

chore(release): 1.7.0 [skip ci]

---

.github/workflows/ci.yml

- fix: ci android setup potential fix

fix: ci android setup potential fix

---

example/src/App.tsx
example/src/components/CustomNodeRowView.tsx
example/src/screens/CustomArrowScreen.tsx
example/src/screens/CustomCheckboxScreen.tsx
example/src/screens/CustomNodeIDScreen.tsx
example/src/screens/CustomNodeRowViewScreen.tsx
example/src/screens/LargeDataScreen.tsx
example/src/screens/MediumDataScreen.tsx
example/src/screens/SmallDataScreen.tsx
example/src/utils/sampleDataGenerator.ts
src/TreeView.tsx
src/__tests__/treeNode.helper.test.ts
src/components/NodeList.tsx
src/helpers/expandCollapse.helper.ts
src/helpers/flattenTree.helper.ts
src/helpers/search.helper.ts
src/helpers/selectAll.helper.ts
src/helpers/toggleCheckbox.helper.ts
src/helpers/treeNode.helper.ts
src/store/treeView.store.ts
src/types/treeView.types.ts
src/utils/typedMemo.ts

the type for the ID will still default to being a string.
closes #42

[feat] allow any type for tree node IDs

---

example/package.json
example/yarn.lock
package-lock.json
package.json
yarn.lock

fix: upgraded some deps

---

README.md

- docs: fixed broken readme header hyperlinks

docs: fixed broken readme header hyperlinks

---

example/ios/Podfile.lock
example/package.json
example/yarn.lock
package-lock.json
package.json
patches/react-native-paper+5.13.1.patch
src/__mocks__/zustand.ts
src/__tests__/selectAll.helper.test.ts
src/components/NodeList.tsx
src/store/treeView.store.ts
tsconfig.json
yarn.lock

- fix: upgraded zustand to v5 and upgraded other deps
- style: lint cleanup

Upgraded zustand to v5 and upgraded other deps

---

.github/workflows/ci.yml

- ci: attempt to fix requirement of package json lock to satify ci

ci: attempt to fix requirement of package json lock to satify ci

---

.github/workflows/beta-release.yml

- ci: removed npm ci from beta release gh actions pipeline

ci: removed npm ci from beta release gh actions pipeline  @JairajJangle

---

.github/workflows/beta-release.yml

- ci: fixed incorrect beta releae ref name

ci: fixed incorrect beta releae ref name
